<?php

final class Merchandillo_Logs_Tab_Filter_Form_Renderer
{
    /** @var Merchandillo_Log_Manager_Interface */
    private $logManager;

    /** @var string */
    private $pageSlug;

    /** @var string */
    private $actionKey;

    /** @var string */
    private $nonceAction;

    public function __construct(
        Merchandillo_Log_Manager_Interface $logManager,
        string $pageSlug,
        string $actionKey,
        string $nonceAction
    ) {
        $this->logManager = $logManager;
        $this->pageSlug = $pageSlug;
        $this->actionKey = $actionKey;
        $this->nonceAction = $nonceAction;
    }

    /**
     * @param array{file:string,level:string,search:string,limit:int} $filters
     * @param array<string,string> $logFiles
     */
    public function render(
        array $filters,
        array $logFiles,
        int $entryCount,
        string $logsTabUrl,
        string $lastHundredUrl,
        string $exportUrl
    ): void {
        echo '<p class="mwb-section-description">' . esc_html__('Inspect, filter, export, and clear plugin log files generated by sync attempts.', 'merchandillo-woocommerce-bridge') . '</p>';

        echo '<form method="get" action="' . esc_url(admin_url('options-general.php')) . '" class="mwb-log-filters">';
        echo '<input type="hidden" name="page" value="' . esc_attr($this->pageSlug) . '" />';
        echo '<input type="hidden" name="tab" value="logs" />';
        echo '<div class="mwb-filter-grid">';

        $this->render_file_filter($filters, $logFiles);
        $this->render_level_filter($filters);
        $this->render_search_filter($filters);
        $this->render_limit_filter($filters);

        echo '<p class="mwb-filter-field mwb-filter-submit">';
        echo '<button type="submit" class="button button-primary mwb-btn-primary">' . esc_html__('Apply Filters', 'merchandillo-woocommerce-bridge') . '</button>';
        echo '</p>';

        echo '</div>';
        echo '</form>';

        $this->render_action_buttons($logsTabUrl, $lastHundredUrl, $exportUrl);
        $this->render_summary($entryCount, (int) $filters['limit']);
    }

    /**
     * @param array{file:string,level:string,search:string,limit:int} $filters
     * @param array<string,string> $logFiles
     */
    private function render_file_filter(array $filters, array $logFiles): void
    {
        echo '<p class="mwb-filter-field">';
        echo '<label for="merchandillo-log-file" class="mwb-label">' . esc_html__('Log File', 'merchandillo-woocommerce-bridge') . '</label>';
        echo '<select id="merchandillo-log-file" name="log_file" class="mwb-input mwb-select">';
        echo '<option value="all"' . selected($filters['file'], 'all', false) . '>' . esc_html__('All files', 'merchandillo-woocommerce-bridge') . '</option>';
        foreach ($logFiles as $fileName => $path) {
            $fileLabel = $this->logManager->format_file_option_label($fileName, $path);
            echo '<option value="' . esc_attr($fileName) . '"' . selected($filters['file'], $fileName, false) . '>' . esc_html($fileLabel) . '</option>';
        }
        echo '</select>';
        echo '</p>';
    }

    /**
     * @param array{file:string,level:string,search:string,limit:int} $filters
     */
    private function render_level_filter(array $filters): void
    {
        echo '<p class="mwb-filter-field">';
        echo '<label for="merchandillo-log-level" class="mwb-label">' . esc_html__('Level', 'merchandillo-woocommerce-bridge') . '</label>';
        echo '<select id="merchandillo-log-level" name="log_level" class="mwb-input mwb-select">';
        echo '<option value=""' . selected($filters['level'], '', false) . '>' . esc_html__('All levels', 'merchandillo-woocommerce-bridge') . '</option>';
        foreach ($this->logManager->get_allowed_levels() as $level) {
            echo '<option value="' . esc_attr($level) . '"' . selected($filters['level'], $level, false) . '>' . esc_html(strtoupper($level)) . '</option>';
        }
        echo '</select>';
        echo '</p>';
    }

    /**
     * @param array{file:string,level:string,search:string,limit:int} $filters
     */
    private function render_search_filter(array $filters): void
    {
        echo '<p class="mwb-filter-field">';
        echo '<label for="merchandillo-log-search" class="mwb-label">' . esc_html__('Contains Text', 'merchandillo-woocommerce-bridge') . '</label>';
        echo '<input id="merchandillo-log-search" type="text" name="log_search" value="' . esc_attr($filters['search']) . '" class="regular-text mwb-input" />';
        echo '</p>';
    }

    /**
     * @param array{file:string,level:string,search:string,limit:int} $filters
     */
    private function render_limit_filter(array $filters): void
    {
        echo '<p class="mwb-filter-field mwb-filter-limit">';
        echo '<label for="merchandillo-log-limit" class="mwb-label">' . esc_html__('Line Limit', 'merchandillo-woocommerce-bridge') . '</label>';
        echo '<input id="merchandillo-log-limit" type="number" min="1" max="5000" step="1" name="log_limit" value="' . esc_attr((string) $filters['limit']) . '" class="mwb-input" />';
        echo '</p>';
    }

    private function render_action_buttons(string $logsTabUrl, string $lastHundredUrl, string $exportUrl): void
    {
        echo '<div class="mwb-log-actions">';
        echo '<a href="' . esc_url($lastHundredUrl) . '" class="button mwb-btn-secondary">' . esc_html__('Show Last 100 Lines', 'merchandillo-woocommerce-bridge') . '</a>';
        echo '<a href="' . esc_url($exportUrl) . '" class="button mwb-btn-secondary">' . esc_html__('Export Filtered Logs', 'merchandillo-woocommerce-bridge') . '</a>';
        echo '<form method="post" action="' . esc_url($logsTabUrl) . '" class="mwb-inline-form">';
        wp_nonce_field($this->nonceAction);
        echo '<input type="hidden" name="' . esc_attr($this->actionKey) . '" value="clear" />';
        echo '<input type="hidden" name="page" value="' . esc_attr($this->pageSlug) . '" />';
        echo '<input type="hidden" name="tab" value="logs" />';
        echo '<button type="submit" class="button mwb-btn-danger" onclick="return confirm(\'' . esc_js(__('Are you sure you want to delete all plugin log files?', 'merchandillo-woocommerce-bridge')) . '\');">' . esc_html__('Clear Plugin Logs', 'merchandillo-woocommerce-bridge') . '</button>';
        echo '</form>';
        echo '</div>';
    }

    private function render_summary(int $entryCount, int $lineLimit): void
    {
        echo '<p class="description mwb-help">';
        echo esc_html(
            sprintf(
                __('Showing %1$d log entries with the current filters (limit: %2$d).', 'merchandillo-woocommerce-bridge'),
                $entryCount,
                $lineLimit
            )
        );
        echo '</p>';
    }
}
