<?php

final class Merchandillo_Translation_Dictionary
{
    /**
     * @return array<string,string>
     */
    public function greek_catalog(): array
    {
        return [
            'Merchandillo Sync' => 'Συγχρονισμός Merchandillo',
            'Platform Credentials' => 'Διαπιστευτήρια Πλατφόρμας',
            'Enable Sync' => 'Ενεργοποίηση Συγχρονισμού',
            'API Base URL' => 'Βασικό URL API',
            'API Key' => 'Κλειδί API',
            'API Secret' => 'Μυστικό API',
            'Language' => 'Γλώσσα',
            'Log Errors' => 'Καταγραφή Σφαλμάτων',
            'Save Settings' => 'Αποθήκευση Ρυθμίσεων',
            'Configure API credentials for pushing order updates to Merchandillo. Failed sync attempts are logged and never break WooCommerce checkout. Use the Logs tab to inspect, export, and clear plugin logs.' => 'Ρυθμίστε τα διαπιστευτήρια API για αποστολή ενημερώσεων παραγγελιών στο Merchandillo. Οι αποτυχημένες προσπάθειες συγχρονισμού καταγράφονται και δεν επηρεάζουν ποτέ το checkout του WooCommerce. Χρησιμοποιήστε την καρτέλα Καταγραφές για προβολή, εξαγωγή και εκκαθάριση των logs.',
            'Queue order sync on create/update/status change' => 'Προσθήκη συγχρονισμού παραγγελίας σε ουρά κατά δημιουργία/ενημέρωση/αλλαγή κατάστασης',
            'Example: https://data.merchandillo.com' => 'Παράδειγμα: https://data.merchandillo.com',
            'Leave empty to keep the current secret.' => 'Αφήστε κενό για να διατηρηθεί το τρέχον μυστικό.',
            'Write sync failures to WooCommerce logs' => 'Καταγραφή αποτυχιών συγχρονισμού στα logs του WooCommerce',
            'Enter API Base URL, API Key, and API Secret to enable API connection tests.' => 'Συμπληρώστε API Base URL, API Key και API Secret για να ενεργοποιηθούν οι δοκιμές σύνδεσης API.',
            'Test API Connection' => 'Δοκιμή Σύνδεσης API',
            'English' => 'Αγγλικά',
            'Greek' => 'Ελληνικά',
            'Merchandillo Bridge for WooCommerce' => 'Γέφυρα Merchandillo για WooCommerce',
            'Sync order changes with confidence using modern controls for API credentials and live log diagnostics.' => 'Συγχρονίστε αλλαγές παραγγελιών με ασφάλεια, χρησιμοποιώντας σύγχρονα εργαλεία για διαπιστευτήρια API και διάγνωση logs σε πραγματικό χρόνο.',
            'Register at Merchandillo.com' => 'Εγγραφή στο Merchandillo.com',
            'Settings' => 'Ρυθμίσεις',
            'Logs' => 'Καταγραφές',
            'Inspect, filter, export, and clear plugin log files generated by sync attempts.' => 'Προβολή, φιλτράρισμα, εξαγωγή και εκκαθάριση αρχείων log του plugin που δημιουργούνται από προσπάθειες συγχρονισμού.',
            'Apply Filters' => 'Εφαρμογή Φίλτρων',
            'Log File' => 'Αρχείο Log',
            'All files' => 'Όλα τα αρχεία',
            'Level' => 'Επίπεδο',
            'All levels' => 'Όλα τα επίπεδα',
            'Contains Text' => 'Περιέχει Κείμενο',
            'Line Limit' => 'Όριο Γραμμών',
            'Show Last 100 Lines' => 'Εμφάνιση Τελευταίων 100 Γραμμών',
            'Export Filtered Logs' => 'Εξαγωγή Φιλτραρισμένων Logs',
            'Are you sure you want to delete all plugin log files?' => 'Είστε βέβαιοι ότι θέλετε να διαγράψετε όλα τα αρχεία log του plugin;',
            'Clear Plugin Logs' => 'Εκκαθάριση Logs Plugin',
            'Showing %1$d log entries with the current filters (limit: %2$d).' => 'Εμφάνιση %1$d εγγραφών log με τα τρέχοντα φίλτρα (όριο: %2$d).',
            'Timestamp' => 'Χρονική Σήμανση',
            'Log Line' => 'Γραμμή Log',
            'File' => 'Αρχείο',
            'No log entries matched the current filters.' => 'Δεν βρέθηκαν εγγραφές log με τα τρέχοντα φίλτρα.',
            'Removed %1$d log file(s), but %2$d could not be deleted.' => 'Αφαιρέθηκαν %1$d αρχεία log, αλλά %2$d δεν ήταν δυνατό να διαγραφούν.',
            'Removed %d log file(s).' => 'Αφαιρέθηκαν %d αρχεία log.',
            'No plugin log files were found to clear.' => 'Δεν βρέθηκαν αρχεία log του plugin για εκκαθάριση.',
            'API connection test succeeded (HTTP %d).' => 'Η δοκιμή σύνδεσης API πέτυχε (HTTP %d).',
            'API connection test reached Merchandillo successfully (HTTP %d). The endpoint rejected test payload data, which is expected.' => 'Η δοκιμή σύνδεσης API έφτασε επιτυχώς στο Merchandillo (HTTP %d). Το endpoint απέρριψε τα δοκιμαστικά δεδομένα, κάτι αναμενόμενο.',
            'API connection test failed: credentials were rejected (HTTP %d).' => 'Η δοκιμή σύνδεσης API απέτυχε: τα διαπιστευτήρια απορρίφθηκαν (HTTP %d).',
            'API connection test failed: endpoint not found (HTTP %d).' => 'Η δοκιμή σύνδεσης API απέτυχε: το endpoint δεν βρέθηκε (HTTP %d).',
            'API connection test reached Merchandillo, but the server returned an error (HTTP %d).' => 'Η δοκιμή σύνδεσης API έφτασε στο Merchandillo, αλλά ο server επέστρεψε σφάλμα (HTTP %d).',
            'API connection test could not run because API settings are incomplete.' => 'Η δοκιμή σύνδεσης API δεν μπόρεσε να εκτελεστεί επειδή οι ρυθμίσεις API είναι ελλιπείς.',
            'API connection test failed because the request could not be completed.' => 'Η δοκιμή σύνδεσης API απέτυχε επειδή δεν ήταν δυνατό να ολοκληρωθεί το αίτημα.',
            'API connection test returned an unexpected HTTP status (%d).' => 'Η δοκιμή σύνδεσης API επέστρεψε μη αναμενόμενο HTTP status (%d).',
            'API connection test finished with an unknown result.' => 'Η δοκιμή σύνδεσης API ολοκληρώθηκε με άγνωστο αποτέλεσμα.',
            'There was a problem syncing that order because API settings are missing.' => 'Παρουσιάστηκε πρόβλημα συγχρονισμού της παραγγελίας επειδή λείπουν ρυθμίσεις API.',
            'There was a problem syncing that order because it could not be loaded.' => 'Παρουσιάστηκε πρόβλημα συγχρονισμού της παραγγελίας επειδή δεν ήταν δυνατή η φόρτωσή της.',
            'There was a problem syncing that order to Merchandillo.' => 'Παρουσιάστηκε πρόβλημα συγχρονισμού της παραγγελίας με το Merchandillo.',
            'API connection test failed.' => 'Η δοκιμή σύνδεσης API απέτυχε.',
        ];
    }
}
